### ISSUE TITLE
Boards not aligning correctly 0.2.6

### ISSUE THREAD

**Issue by cmoafr** [JimmyCushnie/TUNG#43] opened 2018-09-19 19:51 UTC
The bug where board aren't aligning correctly in 0.2.6 is not completely fixed.
![image](https://user-images.githubusercontent.com/43421239/45776889-93ef2c00-bc54-11e8-9677-ead05f63147f.png)

How to recreate it :
![image](https://user-images.githubusercontent.com/43421239/45777394-f563ca80-bc55-11e8-9915-c4abebf08eed.png)

I had to do this to centre it on a pillar but the one I already made started on the side.

**Comment by cmoafr** [comment] 2018-09-19 19:53
Original setup :
![image](https://user-images.githubusercontent.com/43421239/45777579-7de26b00-bc56-11e8-8205-5c51a3a2dbdc.png)

**Comment by JimmyCushnie** [comment] 2018-09-19 22:29
I am unable to reproduce.
![2018-09-19_18-14-01](https://user-images.githubusercontent.com/32693298/45785298-cd666e00-bc39-11e8-9251-f3bc59ac2ea6.jpg)
![2018-09-19_18-14-10](https://user-images.githubusercontent.com/32693298/45785299-cd666e00-bc39-11e8-8fdb-67678d083219.jpg)
![2018-09-19_18-14-19](https://user-images.githubusercontent.com/32693298/45785297-cd666e00-bc39-11e8-81a9-c3e1da6b28bc.jpg)

**Comment by cmoafr** [comment] 2018-09-21 18:13
well, that's weird ...

![image](https://user-images.githubusercontent.com/43421239/45898620-c3c83c00-bdda-11e8-9394-f650807eb3ae.png)

ok, so I just had to reinstall the game ...

**Comment by JimmyCushnie** [comment] 2018-09-21 18:59
Perhaps there were still some files from an older version of the game where the bug wasn't fixed? Hm. I'm glad it's working for you now :)

I'm going to close this issue, but if it happens to you again, please let me know.

**Closed as completed by JimmyCushnie** 2018-09-21 18:59 UTC
