### ISSUE TITLE
Right click ghost behavior

### ISSUE THREAD

**Issue by Vykori** [JimmyCushnie/TUNG#34] opened 2018-04-03 01:44 UTC
With ghosts enabled (capslock), when you're looking at the ground, if you right-click, the ghost will stick in that position. Once you left click, it places where you're looking, the stuck ghost will disappear, and ghosts become disabled. You have to toggle it on again with capslock.

**Comment by pipe01** [comment] 2018-04-03 15:48
#26 I guess was it wasn't because of a mod then lol

**Comment by Vykori** [comment] 2018-04-03 15:52
wow oops, I should've tested without mods before I posted the bug report. I'm a bad debugger. Happy to report it still happens on a clean version of the game though lol

**Comment by ForLoveOfCats** [comment] 2018-04-03 19:29
I cannot reproduce.

**TUNG Version:** 0.2.4
**Mods or Addons:** None
**OS:** Manjaro GNU/Linux x64 w/ Plasma 5

**Comment by chrizzz** [comment] 2018-04-03 19:36
I can reproduce in vanilla version 0.2.4 on windows.
https://www.youtube.com/watch?v=D5N4sG-vhEs

**Comment by JimmyCushnie** [comment] 2018-04-05 22:59
Fixed in 0.2.5

**Closed as completed** 2018-04-06 01:37 UTC
