### ISSUE TITLE
issues with rotation locked status message on HUD

### ISSUE THREAD

**Issue by Vykori** [JimmyCushnie/TUNG#23] opened 2018-03-25 02:18 UTC
if you turn OFF ghosts with caps lock, and you lock your rotation with R, the HUD properly says your rotation is locked. if you stare into the distance and press R to unlock your rotation, the HUD doesn't update even though your rotation is now unlocked. This bug does not occur (for me) when ghosts are turned on.

also noteworthy, you can lock your rotation when ghosts are enabled by pressing R when staring at the ghost of the item you're about to place. you cannot lock your rotation this way with ghosts disabled, you have to stare at an item that is already placed (like was normal, before 0.2)

**Comment by JimmyCushnie** [comment] 2018-03-25 05:15
Fixed in 0.2.3. The second part is intended behavior.

**Closed as completed by JimmyCushnie** 2018-03-25 05:15 UTC
